- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - periodic-stable-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - release-notes-jobs
    check:
      jobs:
        - openstack-tox-pylint:
            voting: false
        - sahara-tests-scenario
        - sahara-tests-tempest
        - openstack-tox-lower-constraints
        - openstack-tox-cover:
            voting: false
        - legacy-grenade-dsvm-sahara:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    gate:
      queue: sahara
      jobs:
        - sahara-tests-scenario
        - sahara-tests-tempest
        - openstack-tox-lower-constraints
    experimental:
      jobs:
        - sahara-buildimages-ambari
        - sahara-buildimages-cloudera
        - sahara-buildimages-mapr
        - sahara-tests-scenario-multinode-spark
        - sahara-tests-scenario-py3
    post:
      jobs:
        - openstack-tox-cover

- job:
    name: sahara-buildimages-base
    nodeset: centos-7
    run: playbooks/buildimages/run.yaml
    timeout: 7200

- job:
    name: sahara-buildimages-ambari
    parent: sahara-buildimages-base
    vars:
      sahara_plugin: ambari

- job:
    name: sahara-buildimages-cloudera
    parent: sahara-buildimages-base
    vars:
      sahara_plugin: cloudera

- job:
    name: sahara-buildimages-mapr
    parent: sahara-buildimages-base
    vars:
      sahara_plugin: mapr
