- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - periodic-stable-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - release-notes-jobs
    check:
      jobs:
        - openstack-tox-pylint:
            voting: false
        - openstack-tox-cover:
            voting: false
    gate:
      queue: sahara
    post:
      jobs:
        - openstack-tox-cover
